import type { Metadata } from "next";
import "./globals.css";
import EudoxusSans from "next/font/local";

export const metadata: Metadata = {
  title: "Dentalist",
  description: "Generated by create next app",
  icons: {
    icon: {
      href: "/assets/logo.svg",
      url: "/assets/logo.svg",
    },
  },
};

const eudoxusSans = EudoxusSans({
  src: "../public/font/EudoxusSans-Regular.ttf",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={eudoxusSans.className}>{children}</body>
    </html>
  );
}
