import type { Metadata } from "next";
import "./globals.css";
import EudoxusSans from "next/font/local";

export const metadata: Metadata = {
  title: "Dentalist",
  description: "Generated by create next app",
};

const eudoxusSans = EudoxusSans({
  src: "../public/font/EudoxusSans-Regular.ttf",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={eudoxusSans.className}>{children}</body>
    </html>
  );
}
